// export const FETCH_TABLE_DATA_REQUEST = 'FETCH_TABLE_DATA_REQUEST';
// export const FETCH_TABLE_DATA_SUCCESS = 'FETCH_TABLE_DATA_SUCCESS';
// export const FETCH_TABLE_DATA_FAILURE = 'FETCH_TABLE_DATA_FAILURE';

// export const FETCH_TASK_DATA_REQUEST = 'FETCH_TASK_DATA_REQUEST';
// export const FETCH_TASK_DATA_SUCCESS = 'FETCH_TASK_DATA_SUCCESS';
// export const FETCH_TASK_DATA_FAILURE = 'FETCH_TASK_DATA_FAILURE';