name: Deploy UI to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        npm install --force

    - name: Build Project
      run: |
        echo "Building the project..."
        npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOSTINGER_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Prepare Remote Directory
      env:
        DEPLOY_PATH: ${{ secrets.UI_DEPLOY_PATH }}
        SERVER_IP: ${{ secrets.HOSTINGER_IP }}
        SERVER_USER: ${{ secrets.HOSTINGER_USER }}
      run: |
        # First, ensure parent directory exists and we have permissions
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo mkdir -p $DEPLOY_PATH && sudo chown -R $SERVER_USER:$SERVER_USER $DEPLOY_PATH"
        
        # Then create the dist directory
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "mkdir -p $DEPLOY_PATH/dist"

    - name: Deploy to Hostinger
      env:
        DEPLOY_PATH: ${{ secrets.UI_DEPLOY_PATH }}
        SERVER_IP: ${{ secrets.HOSTINGER_IP }}
        SERVER_USER: ${{ secrets.HOSTINGER_USER }}
      run: |
        echo "Deploying UI to Hostinger VPS..."
        
        # Debug: Show local directory structure
        echo "Local directory structure:"
        ls -la dist/
        
        # Debug: Show remote directory structure
        echo "Remote directory structure:"
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "ls -la $DEPLOY_PATH"
        
        # Copy new build files to the server with verbose output
        echo "Copying new build files to the server..."
        rsync -avzh -e "ssh -o StrictHostKeyChecking=no" --progress dist/ "$SERVER_USER@$SERVER_IP:$DEPLOY_PATH/dist/"

    - name: Verify Deployment
      env:
        DEPLOY_PATH: ${{ secrets.UI_DEPLOY_PATH }}
        SERVER_IP: ${{ secrets.HOSTINGER_IP }}
        SERVER_USER: ${{ secrets.HOSTINGER_USER }}
      run: |
        echo "Verifying deployment..."
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "ls -la $DEPLOY_PATH/dist"

    - name: Restart Nginx
      env:
        SERVER_IP: ${{ secrets.HOSTINGER_IP }}
        SERVER_USER: ${{ secrets.HOSTINGER_USER }}
      run: |
        echo "Restarting Nginx..."
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo systemctl reload nginx"