name: Deploy UI to Hostinger VPS

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        echo "Installing dependencies..."
        npm install --force

    - name: Build Project
      run: |
        echo "Building the project..."
        npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOSTINGER_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Deploy to Hostinger
      run: |
        echo "Deploying UI to Hostinger VPS..."
        ssh -T -o StrictHostKeyChecking=no root@${{ secrets.HOSTINGER_IP }} << EOF
          # Navigate to the deployment path
          cd ${{ secrets.UI_DEPLOY_PATH }}

          # Remove the existing 'dist' folder if it exists
          if [ -d "dist" ]; then
            echo "Removing existing 'dist' folder..."
            sudo rm -rf dist
          fi

          # Ensure the deployment path structure remains intact
          echo "Deployment path verified."
        EOF

        # Copy new 'dist' folder to the deployment path
        echo "Copying new build files to the server..."
        rsync -avz ./dist ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_IP }}:${{ secrets.UI_DEPLOY_PATH }}/

    - name: Restart Nginx (Optional)
      run: |
        echo "Restarting Nginx..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_IP }} << EOF
          sudo systemctl reload nginx
        EOF
